- RtMidi.cpp
Without this they still "hang around" even after being closed, references:
- https://github.com/justinlatimer/node-midi/pull/96
- https://github.com/justinlatimer/node-midi/issues/75
> fix virtual ports closing in OSX

- autogen.sh
- configure.ac
Some users are having trouble running the autotools programs in the correct order.  The presence of a script to do so can be useful, and is commonly called autogen.sh.  This PR adds such a script to rtmidi, and also enables a couple of nice automake features, (silent build and maintainer mode).
Should fix #56 and #45.
> Add autogen.sh script

- tests/Makefile.am
This stops automake from generating filenames like "midiprobe-midiprobe.o".
> Use the same options for all test programs.

- Makefile.am
- autogen.sh
- configure.ac
This is on top of PR #58 , but I made it a separate PR because it might need discussion. I noticed when compiling that the version appended to the .so was incorrect.  Importantly, in other projects, this 3-digit number is _not_ the release number of the software, but rather is a compatibility indicator.  The rules of thumb for updating the number can be seen in the changes to configure.ac.  I left it at 1.0.0 because i wasn't sure what it should be for RtMidi.  I propose adding this to RtMidi as a way of tracking forwards- and backwards API compatibility, but the PR should be fixed to have an appropriate number as compared to previous releases.
> Lt so version

- configure.ac
- doc/doxygen/Doxyfile.in
- rtmidi.pc.in
Sorry for the annoying post-release PR... i noticed that the version number in rtmidi.pc was not updated.  (It happens!)
So, this PR proposes to get this from the autoconf variable.  Also, to ensure consistency between the version number listed in configure.ac and RtMidi.h, it adds a test to configure.ac that compares them and errors out if they are different.
(The alternative would be to remove `#define RTMIDI_VERSION` from RtMidi.h, or have RtMidi.h be a generated file, but these solutions seem to me to be more annoying than just automatically checking it..)
> Fix version in rtmidi.pc

- autogen.sh
- configure.ac
Just stops autoreconf complaining about the config directory if it's not there, and also removes some unnecessary left-over AC_SUBSTs.
> A couple of not very urgent patches to configure.ac and autogen.sh.

- RtMidi.cpp
In order to debug connection issue, I added the error code return by *MIDIClientCreate*. If needed I can add this behavior to other midi error case.
> Add error number when MidiInCore::initialize fails

- RtMidi.cpp
The initializer was lost when changing firstErrorOccured from static to member (c39bb17ab47499fc9827abc100b94fb8c71715ed).
This causes error() to return prematurely and ignore all errors, if an error callback is set and fEO happens to have initialized to `true`.
> Initialize firstErrorOccurred_

- doc/doxygen/Doxyfile.in
- doc/doxygen/samples/getting_started.cpp
- doc/doxygen/tutorial.txt
sample snippets are added to doc/doxygen/samples and
included with \include into doxygen.
this also means, that it is possible to compile the
examples and check, if they are (still) compiling.
> using samples to provide code examples in doxygen

- RtMidi.cpp
This patch makes PureData visible to RtMidi on Linux with alsa
> MidiInAlsa::portInfo: don't filter SND_SEQ_PORT_TYPE_APPLICATION

- RtMidi.cpp
CFRelease call was missing for the temporary CFStringRef (Xcode's leak detector was complaining about it).
> Fix CFStringRef memory leak in MidiOutCore::openPort

- RtMidi.h
In other API functions, the parameter name is already commented out to avoid the aforementioned warning. For `getPortName`, the parameter name is not commented out yet.
> Avoid "unreferenced formal parameter" warning in dummy API.

- rtmidi_c.h
This adds a few things that `gcc` complained about when compiling against `rtmidi_c.h`.
> [rtmidi_c] Add struct and stddef to get compiling under gcc happy

- RtMidi.cpp
- RtMidi.h
- rtmidi_c.cpp
There is no reason forr the sendMessage parameter to not be const. Making it const gives confidence to the user that they can e.g. reuse a message and do not have to re-allocate it.
This pull request also contains another little change in the C wrapper, which avoids the allocation of the data vector on the heap while it can just as well be placed on the stack.
> Make sendMessage param const

- rtmidi_c.cpp
- rtmidi_c.h
I wanted to update my D bindings to the new RtMidi C api. 
However I had the following issues : 
- there was no handling of exception : my own C bindings captured the exception and the error message so that one could recover from an error or explain what was wrong; 
- in `rtmidi_in_get_message` the double return value of `RtMidiIn::getMessage` (number of seconds elapsed) was used to allocate the given `unsigned char ** message` array as if it was the length of the vector passed to `getMessage`; I needed a way to properly allocate the array and copy the data into a D GC allocated one before freeing the C malloc'ed memory.
So, I modified the C api as follow : 
- the RtMidiPtr `typedef`'s are now aliases to a simple structure : 
``` c++
struct RtMidiWrapper {
void* ptr; // The RtMidi pointer …
```
> C api changes

- RtMidi.cpp
* `INVALID_HANDLE_VALUE` is not compatible with `HMIDIIN` if `STRICT` is defined (which should always be the case, except for legacy code bases).
* Unconditional compile error in `midiInputCallback`.
> Compile fixes for WinMM

- RtMidi.cpp
- RtMidi.h
Add a second sendMessage prototype that takes a normal C array instead of std::vector.
From discussion in #118.
> No allocations on sendMessage

- RtMidi.cpp
- rtmidi_c.cpp
Directly pass on the pointer+size for message instead of creating a superfluous vector.
> C API: Make use of new sendMessage overload

- configure.ac
Removed line which adds, when configured with prefix, include to the currently installed version (assuming prefix is always the same).
This include causes submodules (i.e. tests) to link against the currently installed library, instead of the newly compiled one, breaking build when upgrading version.
(I managed to break last pull request, opening new one. Sorry.)
>  Build breaks when compiling with --prefix and upgrading version.

- rtmidi_c.cpp
- rtmidi_c.h
This covers the issues with the C API that I've found when working on Go bindings. Most of them look critical to me, so I dared to make some changes:
1. Replace `typedef RtMidiWrapper* RtMidiPtr;` with `typedef struct RtMidiWrapper* RtMidiPtr;` because the former is invalid C code and doesn't compile in C99 mode.
2. Removed RT_MIDI_API_WINDOWS_KS from the enum to make C API enum absolutely match RtAudio C++ API enum. Otherwise the numeric values will be incorrect. I haven't found any uses of RT_MIDI_API_WINDOWS_KS in the code, so I assumed it's safe to remove it from the C API, if it's not in the C++ API.
3. Removed rtmidi_sizeof_rtmidi_api. Well, this is a matter of taste, but I find `sizeof(enum RtMidiApi)` to be much more readable and explicit. Since the type is defined in the header I …
> C API improvements/fixes

- contrib/go/rtmidi/rtmidi.go
- contrib/go/rtmidi/rtmidi_stub.cpp
- contrib/go/rtmidi/rtmidi_stub.h
- contrib/go/rtmidi/rtmidi_test.go
As discussed in RtAudio thread (https://github.com/thestk/rtaudio/pull/99), this includes RtMidi Go bindings done in absolutely the same manner. Go tools like vet/lint seem to be happy, so I'm making a pull request.
> Add go bindings

- .gitattributes
- Makefile.am
- RtMidi.cpp
- RtMidi.h
- configure.ac
- rtmidi.pc.in
this includes the Debian patches from #131.
the original patches have been broken up and re-submitted in what i think are more atomic pieces.
some of the more dubious parts of the patches have been removed entirely (e.g. the `PC_FILE` stuff).
things that still need to be resolved:
> Debian changes

- RtMidi.cpp
Just a couple of places weren't following Core Foundation's 'Create Rule'.
> Mac leak fixes for CFStringCreateWithCString without matching CFRelease

- RtMidi.cpp
- RtMidi.h
The ALSA Sequencer API supports the re-setting of the client name after
the client has been created. JACK doesn't appear to support this yet
(though there way be a way using the metadata API). Other API's may
support this, but haven't been tested. This commit adds the method
setClientName(const std::string &clientName) to the RtMidi class. For
the API's for which this has not been implemented, a warning is thrown
using the RtMidiError system.
> add setClientName() functionality

- RtMidi.cpp
- RtMidi.h
- configure.ac
This commit adds a new method setPortName(const std::string &portName)
to the RtMidi class. Port renaming is implemented for the ALSA and
JACK API's. For the other API's, a warning is thrown using RtMidiError.
Note that port renaming in JACK is implemented using jack_port_rename(),
which is available on jack2 versions >= 1.9.11, and jack1 versions >=
0.125.0.
> add setPortName() functionality

- CMakeLists.txt
1. Since both UNIX and APPLE are defined, the ALSA option needs further disambiguation.
2. Fix a bad path when using rtmid as a subproject.
> Fix a couple of problems when using cmake to build on macOS

- .gitignore
The only files generated by a build, which are not in this ignore list yet, are the test program binaries. The can't really be ignored via a simple pattern and I didn't want to list them individually. But I can enhance this PR by adding them as well, if so desired.
> Improve gitignore rules to ignore most generated files

- CMakeLists.txt
There's a common technique with CMake where instead of building and installing your dependencies, you check your dependencies into your project as git submodules and then use add_subdirectory to make them build at the same time your project builds. This is good because it gets you reproducible builds and your versioning is enforced by git.
Right now RTMIDI does not work with add_subdirectory because it has variables/targets that are likely to namespace collide with other CMakeLists. For example right now if you use add_subdirectory to include RTMIDI and PhysFS in the same build it cannot build because they both declare a target named "uninstall" and CMake bails out when it sees this.
This patch fixes this by:
- "Namespace" option variables with RTMIDI_
- New RTMIDI_TARGETNAME_UNINSTALL …
> Changes to CMakeLists to make use with add_subdirectory easier

- contrib/go/rtmidi/rtmidi.go
This code failed to build on Go 1.12 with the error:
`rtmidi.go:75:39: identifier "_Ctype_uint" may conflict with identifiers generated by cgo`
This change seems to be the proper way to convert between C types in cgo and fixes this error.
> Fix Go binding compilation error

- CMakeLists.txt
- Makefile.am
- RtMidi.cpp
- RtMidi.h
- rtmidi_c.cpp
- rtmidi_c.h
- tests/Makefile.am
- tests/apinames.cpp
This is identical to a proposed enhancement for RtAudio.  https://github.com/thestk/rtaudio/pull/136
In short: it's an ability to get API names, and to look up APIs according to names.
Only difference: the C interface has different signature for querying the APIs.
The implementation and the test have received a minor modification.
> API names, and conversion from/to API identifier

- rtmidi_c.h
I'm using libclang to parse the header, and it's getting confused by the protos for the two "no argument" functions.
This change won't affect the behaviour at all, but is apparently [more correct, for C at least](https://stackoverflow.com/questions/693788/is-it-better-to-use-c-void-arguments-void-foovoid-or-not-void-foo), and will help libclang parse the header file cleanly.
> correct C no-arg function prototypes

- RtMidi.cpp
This repairs a problem introduced by commit 3155671
"alsa: fix a switch fallthrough warning", which makes it impossible to
receive any system-exclusive message.
> Fix the input of system-exclusive messages on ALSA

- RtMidi.cpp
The function `isPortOpen()` always returns `false` on JACK because the member variable `connected_` is never set.
I make it behave the same as other APIs : set to `true` after a non-virtual port opened, `false` after closed.
> jack: track the current port state, fix isPortOpen()

- RtMidi.h
This allows client code to be compiled with `-Wold-style-cast`
> Removed old-style casts in public header.

- RtMidi.cpp
- RtMidi.h
This is a whitespace / line-breaks change only. No changes in the actual code or functionality.
* Fixes inconsistent indentation of if/else statements, blocks, function parameters and class attribute initializers.
* Fixes inconsistent whitespace within parentheses.
* Removes trailing whitespace.
* Replaces tabs with spaces.
>  Fix code formatting inconsistencies and remove trailing whitespace

- CMakeLists.txt
CoreMidi seems to have been left out of the api list, leaving it empty when
compiling on macOS.
> Add coremidi to the api list when compiling with coremidi

- rtmidi.pc.in
- rtmidi_c.cpp
- rtmidi_c.h
They are indifferent to some users, and pollute diffs for other ones.
> Delete trailing whitespaces.

- rtmidi_c.cpp
The tabulation produces inconsistent alignment in diffs and in som
editors, for no benefit.
> Remove remaining tabulations from source code.

- rtmidi_c.h
It took me a while to figure out what was going wrong because I was passing an uninitialized variable for the size, but apparently the function uses it to check if it's large enough to hold the message. 
```C
double rtmidi_in_get_message (RtMidiInPtr device,
unsigned char *message,
size_t *size)
{
try {
// FIXME: use allocator to achieve efficient buffering
std::vector<unsigned char> v;
double ret = ((RtMidiIn*) device->ptr)->getMessage (&v);
if (v.size () > 0 && v.size() <= *size) { // <---------- here
memcpy (message, v.data (), (int) v.size ());
}
*size = v.size();
return ret;
}
catch (const RtMidiError & err) {
device->ok  = false;
device->msg = err.what ();
return -1;
}
catch (...) {
device->ok  = false;
device->msg = "Unknown error";
return -1;
}
}
```
I've never seen another API do …
> clarify that the value of param size is used by rtmidi_in_get_message

- RtMidi.cpp
Some backends may have an lower-latency way to send out multiple messages at once rather than one at time. This API allows clients to take advantage of that capability.
The first implementation is for `MidiOutAlsa`, which can buffer multiple messages at once before draining them out over the alsa pipe.
> Implement sendMessages

- RtMidi.cpp
Enabled iOS support, based on the modifications suggested by **Sander Pasveer** (sander@velotype.com)
Tested by creating and running `midiprobe.cpp` on iPad with preprocessor macros `__MACOSX_CORE__` and `TARGET_OS_IPHONE` defined. Had an X3Mini connected to iPad using Lighting to USB cable. Midiprobe output:
```
There are 1 MIDI input sources available.
Input Port #1: X3mini
There are 1 MIDI output ports available.
Output Port #1: X3mini
```
> Ios support

- CMakeLists.txt
Currently I need to manually add the include-path for RtMidi.h when using RtMidi. With this pull-request this will not be necessary any more and 
find_package(RtMidi REQUIRED)
target_link_libraries(my-target PRIVATE RtMidi::rtmidi)
will be all that is required to use your library, which is more elegant and less error-prone than manually configuring the include path. Hope you like it:)
> Expose include path for RtMidi.h in target rtmidi

- RtMidi.cpp
The endpoint names of some devices (Impulse25 in my case) have a leading whitespace. 
The extra whitespace causes the the `if` statement at [L1161](https://github.com/thestk/rtmidi/blob/master/RtMidi.cpp#L1161) to evaluate to `true`, whereas it should evaluate to `false`. This causes the name of its ports to be "Impulse__Impulse_" and "Impulse__Impulse_MIDI_In_" (whitespaces replaced with underscores for visibility).
Fixed using CFStringTrim.
Thank you for all of your work in making rtmidi available!
> trim whitespace from endpoint names

- CMakeLists.txt
Regarding my work on the RtMidi conan recipe mentioned [here](https://github.com/thestk/rtmidi/issues/251), I needed to apply this patch which shouldn't have any consequences and would avoid having to patch every next release of the RtMidi recipe:
https://github.com/conan-io/conan-center-index/blob/923cf523d50b1b072ffe3104c1eba83b2649d583/recipes/rtmidi/all/patches/4.0.0-0002-rtmidiconfig-install-location-da51f21.patch
Would you mind mergin this?
> Fix RtMidiConfig.cmake install location

- CMakeLists.txt
This is because merely including CTest will actually enable
testing by calling CMakes enable_testing() function.
Without this fix, a parent project that includes RtMidi as a submodule
will have testing enabled which may cause undesirable effects in
other submodules.
> Only include CTest when buliding tests.

- CMakeLists.txt
This command is only needed by:
- users of Xcode <3.0 (2009) and macOS <10.5
- users of CMake older than 3.0.
They can still set to OLD as necessary.
Other CMakers get an error and have to edit CMakeLists.txt.
Here is the link to the policy details.
https://cmake.org/cmake/help/latest/policy/CMP0042.html
Here is a link explaining why and how to use @rpath:
https://www.dribin.org/dave/blog/archives/2009/11/15/rpath/
The OLD behaviour of a policy is deprecated by definition.
CMake 3.16.0-rc3 is the current version.
MACOSX_RPATH is enabled by default.
> [CMakeLists] Remove line 154 cmake_policy(SET CMP0042 OLD)

- CMakeLists.txt
- RtMidi-config.cmake.in
Include directories are't transitively added to other projects using the CMake package config file since the include directory wasn't marked as public.
Additionally moved the CMake thread target into the same package install file by linking it publicly. 
Finally, I replaced the hand-generated RtMidiConfig.cmake file with one generated by CMake's CMakePackageConfigHelpers macros.
> Updated CMake package installation to expose public includes

- CMakeLists.txt
A `-D` is missing when defining `JACK_HAS_PORT_RENAME`, which compiles fine but causes malformed cflags in the pkgconfig file
```
Cflags: -pthread -I${includedir} -D__UNIX_JACK__ JACK_HAS_PORT_RENAME -D__LINUX_ALSA__
```
leading to compilation failures in depending projects.
> g++: error: JACK_HAS_PORT_RENAME: No such file or directory
---
The `prefix` variable in the pkg-config file is never defined prior to its substitution, resulting in an empty prefix value no matter what the user defined. This may cause compiling & linking issues if the lib & header variables fail to resolve relative to the user's desired, non-standard prefix.
```
prefix=
```
After fix:
```
prefix=/nix/store/id9a2ll55pkshhgji0mn4gk6xzxnhqx5-rtmidi-4.0.0
```
---
The CMake build installs the wrong amount of headers to …
> CMake: Minor fixes

- RtMidi.cpp
In this work, I try to make buffered Jack output more robust, as I discovered a few annoyances.
It enables some recovery from failures.
- When a message is written to the ring buffer by `sendMessage`, the outcome is not checked.
If a message too big for the remaining buffer is written, and then passes a short message which succeeds, the validity of the message stream following is potentially broken.
(because the size was communicated onto the size buffer, despite that message data did not go through, or just partial)
- The call `jack_midi_event_reserve` can fail with NULL.
This case should be checked to prevent crashing. In this case, I will discard the buffered event, also permitting the stream to get back on its feet.
```
- If the MIDI processor cannot reserve the event memory, handle …
```
> Improve JACK midi robustness

- CMakeLists.txt
- tests/Makefile.am
- tests/testcapi.c
This just makes sure the C API can be linked, it does not (yet?) exercise the full API, but better than nothing.
> Add a minimal test program for the C API.

- rtmidi.pc.in
This makes it possible to get the appropriate requirements if you pass `--static` to
pkg-config, but otherwise direct links to the API libs are not necessary when dynamically
linking.
Closes #204.
> Change "Requires:" to "Requires.private:" in rtmidi.pc

- rtmidi_c.cpp
- rtmidi_c.h
The address sanitizer warned of a leak in our code linked to rtmidi_get_port_name. One fix could be to just let the recipient of the char * free it. But when compiled as a dll I think that can lead to strange behavior if the standard libraries used in dll and main application differ. So I propose changing the interface of the rtmidi_get_port_name function so the user of it provides a char buffer for it to write into.
> Fix memory leak from rtmidi_get_port_name

- RtMidi.cpp
This disables the call to midiOutReset.
The idea in #222 was to make it optional but it's not clear what the best way to accomplish that is.
In the meantime it seems pretty obvious that sending unsolicited MIDI messages is undesirable?
> WinMM: Disable midiOutReset.

- RtMidi.cpp
This is just a simple approach to the issue raised in #226.  I looked for a more general way to get error messages from Jack but it seems like you have to register one global error handler -- and I'm not sure the warning would help for the issue.  So, this just seems like the simplest approach for this particular situation, just explicitly checking the length of the string against `jack_port_name_size()` and issuing an extra bit of information.
> Jack: Check port name against port name size on failure to open.

- RtMidi.cpp
- RtMidi.h
Hello,
I have been trying to bring [JUCE](https://github.com/WeAreROLI/JUCE) audio plugins to the web using [Dreamtonics/juce_emscripten](https://github.com/Dreamtonics/juce_emscripten/).
When I thought of MIDI support there, I though that adding Web MIDI support to RtMidi would make it nicer as other people would benefit wasm support too.
Therefore, this changeset brings in Web MIDI API support.
It is enabled when  `__WEB_MIDI_API__` is defined. I'm not sure what is good for ordinal(?) emscripten environment so I left other build script parts untouched.
The changes are already used in https://github.com/Dreamtonics/juce_emscripten/pull/4.
> Add Web MIDI API support with emscripten.

- RtMidi.cpp
Earlier versions of emscripten did not complain about this extra argument
but it became more strict and correctly reports the mismatch.
> [emscripten] fix getPortName() runtime signature mismatch.

- CMakeLists.txt
I noticed behavior similar to https://github.com/PortAudio/portaudio/issues/689.
When running cmake only once before install, the public headers would not get added to the ```RtMidi::rtmidi``` target. Running cmake again adds the headers. It seems that is caused by using a feature of GNUInstallDirs (which I am not familiar with) before including it. The fix proposed in https://github.com/PortAudio/portaudio/pull/690 solves the problem.
> [cmake] Fix use of GNUInstallDirs

- RtMidi.cpp
Use posix sched_yield instead of pthread_yield.
pthread_yield is linux specific sched_yield is
a standard posix function. pthread_yield on linux
is implemented using sched_yield.
This makes the jack plugin work on other
platforms than linux. Fixes build of Jack on NetBSD.
> Use posix sched_yield instead of pthread_yield

- RtMidi.cpp
Fixes errors like
```
source/RtMidi.cpp:44:7: error: 'TARGET_OS_IPHONE' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_]
#if TARGET_OS_IPHONE
^
1 error generated.
```
> RtMidi.cpp: include TargetConditionals.h on Apple platforms

- RtMidi.cpp
This silences two C4018 warnings when compiling the Win32 implementation. One of them could also be turned into a range-based for loop as C++11 is now required, but I kept the changes minimal in this PR.
> Silence signedness comparison warnings

- .gitignore
- contrib/go/rtmidi/go.mod
- contrib/go/rtmidi/rtmidi.go
- contrib/go/rtmidi/rtmidi_stub.cpp
- rtmidi_c.cpp
Trying to rebuild a Go project with the current release, I noticed that _contrib/go/rtmidi_ hasn't kept up with the C++/C library, and wanted to offer some changes to get it working again.
* The API constants aren't being defined as the API type.
* The signature for [rtmidi_get_port_name](https://github.com/thestk/rtmidi/blob/master/rtmidi_c.cpp#L135) changed in commit f922c14.
* A `-std=c++11` flag has been required to build since 3650105.
* Go can't easily build or link with object files elsewhere in the repo, so it `#include`s both _RtMidi.cpp_ and _rtmidi_c.cpp_ and compiles them as a single source file. Unfortunately, there are two symbol collisions introduced after the Go module was committed that prevent this. To remedy this, I propose:
* Renaming the identical …
> Updating contrib/go to work with v5.0.0

- RtMidi.cpp
The `isPortOpen()` function always returns false on web builds. This is to some extent expected as one of the code comments read "In Web MIDI API world, there is no step to open a port", but from an API consistency standpoint it's not so good, especially when working on cross platform code built on top of RtMidi.
In this pull request I set the `connected_` flag when calling `openPort()` and `closePort()` also on the web target of RtMidi.
> Make sure to set the connected_ state also on web

- RtMidi.cpp
If MIDIHDR is not initialized, sometimes midiOutPrepareHeader will return MMSYSERR_INVALPARAM.
> Zero value initiation MIDIHDR to avoid crashes

- RtMidi.h
- configure.ac
Version number parts as numeric defines to let other code use preprocessor conditionals for supporting different versions at compile time.
With this it would be possible to write somtehing like this:
```
#if RTMIDI_VERSION_MAJOR >= 5
...
#else
...
#endif
```
to support different RtAudio versions without the need to use external tools like pkg-config.  
See also https://github.com/thestk/rtaudio/pull/363
> Version number parts as numeric defines

- rtmidi_c.cpp
- rtmidi_c.h
I am the maintainer of the [Perl binding to RtMidi](https://metacpan.org/pod/MIDI::RtMidi::FFI), working on an update for RtMidi 5.0.0. I am currently probing characteristics of various C API components to somewhat-heuristically determine the library version, so I think this will be a useful addition for language binding maintainers.
I've found the C API incredibly useful, as C++ isn't a first-class citizen just yet (that is, calling `RtMidi::getVersion` is non-trivial).
The binding is intended to be installable without necessarily requiring a compiler, so the opportunity to simply pull this value from a header during install is not guaranteed.
Thanks!
> Add rtmidi_get_version() to C API

- RtMidi.cpp
Avoid listing ports that are usually from 3rd.party managers or clients that have no subscriptable ports at all.
> ALSA: Avoid listing ports with SND_SEQ_PORT_CAP_NO_EXPORT (capabilities)

- RtMidi.cpp
Single MIDI packet can contain multiple MIDI messages.
The first message within the packet has time delta relative to previous MIDI packet, but remaining MIDI messages have time delta 0 relative to the first message.
> CoreMIDI: Fix time delta for messages within same MIDI packet

- RtMidi.cpp
In certain circumstances when building a compound port name (for instance, with an IAC bus), the string math to concatenate the bus and driver does not release one of the source strings, causing a CFStringRef leak on macOS.
This fixes it by doing the appropriate CFRelease after string concatenation.
> Fix a CFStringRef leak in RTMidi Port Name

- RtMidi.cpp
Fix another casw where the concatenation of result and str in name creation doesn't release the source which is concated onto result.
Sorry for two PRs here; the condition to tickle this is a bit different than the condition to tickle the other.
> Fix another CFStr reference leak

- CMakeLists.txt
When dependent projects want to install rtmidi header files, the project CMakeLists will try to search for <Project>/rtmidi.h instead of the actual path of rtmidi.
> Update to CMakeLists.txt to be able to install header files

- RtMidi.cpp
These changes include:
-Changing the Listener constructor to a non-deprecated constructor -Avoiding JNI crashes related to the FindClass method if the method is not called on the main thread
These were necessary changes I had to make for my own code. Perhaps the community will benefit from these changes.
> Modified Android MIDI opening method

- RtMidi.cpp
The clap-wrapper project uses rtmidi for midi purposes, and has a fairly stringent set of compiler warnings enabled (-Wall -Wextra -Wno-unused-parameter -Wpedantic) and this triggers some warnings on MacOS.
This is a fix for these warnings. I've tried to keep within the style of the project, I see other use of static_cast and auto, so this is not the first use here.
> Tidy some compiler warnings

- RtMidi.cpp
With adding android support api the dummy api got lost. This commit adds it again.
> Add support for dummy api again

- rtmidi_c.cpp
Changes `strdup` to `_strdup`
Fixes the following build error on Windows 11 with VS2022:
```
rtmidi_c.cpp(420,19): error C4996: 'strdup': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _strdup. See online help for details.
```
> Fix build error caused by use of deprecated POSIX name of `strdup`
